path_to_ids: "../../dataICD/ids.txt"
path_to_diagnoses: "../../dataICD/all_columns_diagnosisICD10.txt"
ecg_dirs: ["/groups/umcg-endocrinology/tmp02/projects/ukb-55495/data/metaData/v5/xml_T3", "/groups/umcg-endocrinology/tmp02/projects/ukb-55495/data/metaData/v5/xml_T2"]